# Generated by Django 2.0.2 on 2018-06-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180614_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_image',
            new_name='image',
        ),
    ]
